/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppCreationIndexRouteImport } from './routes/app/creation/index'
import { Route as AppContactsIndexRouteImport } from './routes/app/contacts/index'
import { Route as AppProjectsAssistantRouteImport } from './routes/app/projects/assistant'
import { Route as AppCreationWritersRouteImport } from './routes/app/creation/writers'
import { Route as AppCreationResourcesRouteImport } from './routes/app/creation/resources'
import { Route as AppCreationCreateRouteImport } from './routes/app/creation/create'
import { Route as AppContactsListRouteImport } from './routes/app/contacts/list'
import { Route as AppContactsEngageRouteImport } from './routes/app/contacts/engage'
import { Route as AppCreationWritersIndexRouteImport } from './routes/app/creation/writers.index'
import { Route as AppCreationProfilesIndexRouteImport } from './routes/app/creation/profiles/index'
import { Route as AppCreationPersonasIndexRouteImport } from './routes/app/creation/personas/index'
import { Route as AppCreationContentsIndexRouteImport } from './routes/app/creation/contents/index'
import { Route as AppCreationWritersNewRouteImport } from './routes/app/creation/writers.new'
import { Route as AppCreationPersonasNewRouteImport } from './routes/app/creation/personas/new'
import { Route as AppCreationPersonasPersonaIdRouteImport } from './routes/app/creation/personas/$personaId'
import { Route as AppCreationContentsContentIdRouteImport } from './routes/app/creation/contents/$contentId'
import { Route as AppCreationProfilesWritingProfileIdRouteImport } from './routes/app/creation/profiles/writing.$profileId'
import { Route as AppCreationProfilesPsyProfileIdRouteImport } from './routes/app/creation/profiles/psy.$profileId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreationIndexRoute = AppCreationIndexRouteImport.update({
  id: '/creation/',
  path: '/creation/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsAssistantRoute = AppProjectsAssistantRouteImport.update({
  id: '/projects/assistant',
  path: '/projects/assistant',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreationWritersRoute = AppCreationWritersRouteImport.update({
  id: '/creation/writers',
  path: '/creation/writers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreationResourcesRoute = AppCreationResourcesRouteImport.update({
  id: '/creation/resources',
  path: '/creation/resources',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreationCreateRoute = AppCreationCreateRouteImport.update({
  id: '/creation/create',
  path: '/creation/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactsListRoute = AppContactsListRouteImport.update({
  id: '/contacts/list',
  path: '/contacts/list',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactsEngageRoute = AppContactsEngageRouteImport.update({
  id: '/contacts/engage',
  path: '/contacts/engage',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreationWritersIndexRoute = AppCreationWritersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCreationWritersRoute,
} as any)
const AppCreationProfilesIndexRoute =
  AppCreationProfilesIndexRouteImport.update({
    id: '/creation/profiles/',
    path: '/creation/profiles/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCreationPersonasIndexRoute =
  AppCreationPersonasIndexRouteImport.update({
    id: '/creation/personas/',
    path: '/creation/personas/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCreationContentsIndexRoute =
  AppCreationContentsIndexRouteImport.update({
    id: '/creation/contents/',
    path: '/creation/contents/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCreationWritersNewRoute = AppCreationWritersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCreationWritersRoute,
} as any)
const AppCreationPersonasNewRoute = AppCreationPersonasNewRouteImport.update({
  id: '/creation/personas/new',
  path: '/creation/personas/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreationPersonasPersonaIdRoute =
  AppCreationPersonasPersonaIdRouteImport.update({
    id: '/creation/personas/$personaId',
    path: '/creation/personas/$personaId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCreationContentsContentIdRoute =
  AppCreationContentsContentIdRouteImport.update({
    id: '/creation/contents/$contentId',
    path: '/creation/contents/$contentId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCreationProfilesWritingProfileIdRoute =
  AppCreationProfilesWritingProfileIdRouteImport.update({
    id: '/creation/profiles/writing/$profileId',
    path: '/creation/profiles/writing/$profileId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCreationProfilesPsyProfileIdRoute =
  AppCreationProfilesPsyProfileIdRouteImport.update({
    id: '/creation/profiles/psy/$profileId',
    path: '/creation/profiles/psy/$profileId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/contacts/engage': typeof AppContactsEngageRoute
  '/app/contacts/list': typeof AppContactsListRoute
  '/app/creation/create': typeof AppCreationCreateRoute
  '/app/creation/resources': typeof AppCreationResourcesRoute
  '/app/creation/writers': typeof AppCreationWritersRouteWithChildren
  '/app/projects/assistant': typeof AppProjectsAssistantRoute
  '/app/contacts': typeof AppContactsIndexRoute
  '/app/creation': typeof AppCreationIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/creation/contents/$contentId': typeof AppCreationContentsContentIdRoute
  '/app/creation/personas/$personaId': typeof AppCreationPersonasPersonaIdRoute
  '/app/creation/personas/new': typeof AppCreationPersonasNewRoute
  '/app/creation/writers/new': typeof AppCreationWritersNewRoute
  '/app/creation/contents': typeof AppCreationContentsIndexRoute
  '/app/creation/personas': typeof AppCreationPersonasIndexRoute
  '/app/creation/profiles': typeof AppCreationProfilesIndexRoute
  '/app/creation/writers/': typeof AppCreationWritersIndexRoute
  '/app/creation/profiles/psy/$profileId': typeof AppCreationProfilesPsyProfileIdRoute
  '/app/creation/profiles/writing/$profileId': typeof AppCreationProfilesWritingProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/contacts/engage': typeof AppContactsEngageRoute
  '/app/contacts/list': typeof AppContactsListRoute
  '/app/creation/create': typeof AppCreationCreateRoute
  '/app/creation/resources': typeof AppCreationResourcesRoute
  '/app/projects/assistant': typeof AppProjectsAssistantRoute
  '/app/contacts': typeof AppContactsIndexRoute
  '/app/creation': typeof AppCreationIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/creation/contents/$contentId': typeof AppCreationContentsContentIdRoute
  '/app/creation/personas/$personaId': typeof AppCreationPersonasPersonaIdRoute
  '/app/creation/personas/new': typeof AppCreationPersonasNewRoute
  '/app/creation/writers/new': typeof AppCreationWritersNewRoute
  '/app/creation/contents': typeof AppCreationContentsIndexRoute
  '/app/creation/personas': typeof AppCreationPersonasIndexRoute
  '/app/creation/profiles': typeof AppCreationProfilesIndexRoute
  '/app/creation/writers': typeof AppCreationWritersIndexRoute
  '/app/creation/profiles/psy/$profileId': typeof AppCreationProfilesPsyProfileIdRoute
  '/app/creation/profiles/writing/$profileId': typeof AppCreationProfilesWritingProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/contacts/engage': typeof AppContactsEngageRoute
  '/app/contacts/list': typeof AppContactsListRoute
  '/app/creation/create': typeof AppCreationCreateRoute
  '/app/creation/resources': typeof AppCreationResourcesRoute
  '/app/creation/writers': typeof AppCreationWritersRouteWithChildren
  '/app/projects/assistant': typeof AppProjectsAssistantRoute
  '/app/contacts/': typeof AppContactsIndexRoute
  '/app/creation/': typeof AppCreationIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/creation/contents/$contentId': typeof AppCreationContentsContentIdRoute
  '/app/creation/personas/$personaId': typeof AppCreationPersonasPersonaIdRoute
  '/app/creation/personas/new': typeof AppCreationPersonasNewRoute
  '/app/creation/writers/new': typeof AppCreationWritersNewRoute
  '/app/creation/contents/': typeof AppCreationContentsIndexRoute
  '/app/creation/personas/': typeof AppCreationPersonasIndexRoute
  '/app/creation/profiles/': typeof AppCreationProfilesIndexRoute
  '/app/creation/writers/': typeof AppCreationWritersIndexRoute
  '/app/creation/profiles/psy/$profileId': typeof AppCreationProfilesPsyProfileIdRoute
  '/app/creation/profiles/writing/$profileId': typeof AppCreationProfilesWritingProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/settings'
    | '/app/'
    | '/app/contacts/engage'
    | '/app/contacts/list'
    | '/app/creation/create'
    | '/app/creation/resources'
    | '/app/creation/writers'
    | '/app/projects/assistant'
    | '/app/contacts'
    | '/app/creation'
    | '/app/projects'
    | '/app/creation/contents/$contentId'
    | '/app/creation/personas/$personaId'
    | '/app/creation/personas/new'
    | '/app/creation/writers/new'
    | '/app/creation/contents'
    | '/app/creation/personas'
    | '/app/creation/profiles'
    | '/app/creation/writers/'
    | '/app/creation/profiles/psy/$profileId'
    | '/app/creation/profiles/writing/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/settings'
    | '/app'
    | '/app/contacts/engage'
    | '/app/contacts/list'
    | '/app/creation/create'
    | '/app/creation/resources'
    | '/app/projects/assistant'
    | '/app/contacts'
    | '/app/creation'
    | '/app/projects'
    | '/app/creation/contents/$contentId'
    | '/app/creation/personas/$personaId'
    | '/app/creation/personas/new'
    | '/app/creation/writers/new'
    | '/app/creation/contents'
    | '/app/creation/personas'
    | '/app/creation/profiles'
    | '/app/creation/writers'
    | '/app/creation/profiles/psy/$profileId'
    | '/app/creation/profiles/writing/$profileId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/settings'
    | '/app/'
    | '/app/contacts/engage'
    | '/app/contacts/list'
    | '/app/creation/create'
    | '/app/creation/resources'
    | '/app/creation/writers'
    | '/app/projects/assistant'
    | '/app/contacts/'
    | '/app/creation/'
    | '/app/projects/'
    | '/app/creation/contents/$contentId'
    | '/app/creation/personas/$personaId'
    | '/app/creation/personas/new'
    | '/app/creation/writers/new'
    | '/app/creation/contents/'
    | '/app/creation/personas/'
    | '/app/creation/profiles/'
    | '/app/creation/writers/'
    | '/app/creation/profiles/psy/$profileId'
    | '/app/creation/profiles/writing/$profileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/creation/': {
      id: '/app/creation/'
      path: '/creation'
      fullPath: '/app/creation'
      preLoaderRoute: typeof AppCreationIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/contacts/': {
      id: '/app/contacts/'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/assistant': {
      id: '/app/projects/assistant'
      path: '/projects/assistant'
      fullPath: '/app/projects/assistant'
      preLoaderRoute: typeof AppProjectsAssistantRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/creation/writers': {
      id: '/app/creation/writers'
      path: '/creation/writers'
      fullPath: '/app/creation/writers'
      preLoaderRoute: typeof AppCreationWritersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/creation/resources': {
      id: '/app/creation/resources'
      path: '/creation/resources'
      fullPath: '/app/creation/resources'
      preLoaderRoute: typeof AppCreationResourcesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/creation/create': {
      id: '/app/creation/create'
      path: '/creation/create'
      fullPath: '/app/creation/create'
      preLoaderRoute: typeof AppCreationCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/contacts/list': {
      id: '/app/contacts/list'
      path: '/contacts/list'
      fullPath: '/app/contacts/list'
      preLoaderRoute: typeof AppContactsListRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/contacts/engage': {
      id: '/app/contacts/engage'
      path: '/contacts/engage'
      fullPath: '/app/contacts/engage'
      preLoaderRoute: typeof AppContactsEngageRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/creation/writers/': {
      id: '/app/creation/writers/'
      path: '/'
      fullPath: '/app/creation/writers/'
      preLoaderRoute: typeof AppCreationWritersIndexRouteImport
      parentRoute: typeof AppCreationWritersRoute
    }
    '/app/creation/profiles/': {
      id: '/app/creation/profiles/'
      path: '/creation/profiles'
      fullPath: '/app/creation/profiles'
      preLoaderRoute: typeof AppCreationProfilesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/creation/personas/': {
      id: '/app/creation/personas/'
      path: '/creation/personas'
      fullPath: '/app/creation/personas'
      preLoaderRoute: typeof AppCreationPersonasIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/creation/contents/': {
      id: '/app/creation/contents/'
      path: '/creation/contents'
      fullPath: '/app/creation/contents'
      preLoaderRoute: typeof AppCreationContentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/creation/writers/new': {
      id: '/app/creation/writers/new'
      path: '/new'
      fullPath: '/app/creation/writers/new'
      preLoaderRoute: typeof AppCreationWritersNewRouteImport
      parentRoute: typeof AppCreationWritersRoute
    }
    '/app/creation/personas/new': {
      id: '/app/creation/personas/new'
      path: '/creation/personas/new'
      fullPath: '/app/creation/personas/new'
      preLoaderRoute: typeof AppCreationPersonasNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/creation/personas/$personaId': {
      id: '/app/creation/personas/$personaId'
      path: '/creation/personas/$personaId'
      fullPath: '/app/creation/personas/$personaId'
      preLoaderRoute: typeof AppCreationPersonasPersonaIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/creation/contents/$contentId': {
      id: '/app/creation/contents/$contentId'
      path: '/creation/contents/$contentId'
      fullPath: '/app/creation/contents/$contentId'
      preLoaderRoute: typeof AppCreationContentsContentIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/creation/profiles/writing/$profileId': {
      id: '/app/creation/profiles/writing/$profileId'
      path: '/creation/profiles/writing/$profileId'
      fullPath: '/app/creation/profiles/writing/$profileId'
      preLoaderRoute: typeof AppCreationProfilesWritingProfileIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/creation/profiles/psy/$profileId': {
      id: '/app/creation/profiles/psy/$profileId'
      path: '/creation/profiles/psy/$profileId'
      fullPath: '/app/creation/profiles/psy/$profileId'
      preLoaderRoute: typeof AppCreationProfilesPsyProfileIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppCreationWritersRouteChildren {
  AppCreationWritersNewRoute: typeof AppCreationWritersNewRoute
  AppCreationWritersIndexRoute: typeof AppCreationWritersIndexRoute
}

const AppCreationWritersRouteChildren: AppCreationWritersRouteChildren = {
  AppCreationWritersNewRoute: AppCreationWritersNewRoute,
  AppCreationWritersIndexRoute: AppCreationWritersIndexRoute,
}

const AppCreationWritersRouteWithChildren =
  AppCreationWritersRoute._addFileChildren(AppCreationWritersRouteChildren)

interface AppRouteRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppContactsEngageRoute: typeof AppContactsEngageRoute
  AppContactsListRoute: typeof AppContactsListRoute
  AppCreationCreateRoute: typeof AppCreationCreateRoute
  AppCreationResourcesRoute: typeof AppCreationResourcesRoute
  AppCreationWritersRoute: typeof AppCreationWritersRouteWithChildren
  AppProjectsAssistantRoute: typeof AppProjectsAssistantRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppCreationIndexRoute: typeof AppCreationIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppCreationContentsContentIdRoute: typeof AppCreationContentsContentIdRoute
  AppCreationPersonasPersonaIdRoute: typeof AppCreationPersonasPersonaIdRoute
  AppCreationPersonasNewRoute: typeof AppCreationPersonasNewRoute
  AppCreationContentsIndexRoute: typeof AppCreationContentsIndexRoute
  AppCreationPersonasIndexRoute: typeof AppCreationPersonasIndexRoute
  AppCreationProfilesIndexRoute: typeof AppCreationProfilesIndexRoute
  AppCreationProfilesPsyProfileIdRoute: typeof AppCreationProfilesPsyProfileIdRoute
  AppCreationProfilesWritingProfileIdRoute: typeof AppCreationProfilesWritingProfileIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppContactsEngageRoute: AppContactsEngageRoute,
  AppContactsListRoute: AppContactsListRoute,
  AppCreationCreateRoute: AppCreationCreateRoute,
  AppCreationResourcesRoute: AppCreationResourcesRoute,
  AppCreationWritersRoute: AppCreationWritersRouteWithChildren,
  AppProjectsAssistantRoute: AppProjectsAssistantRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppCreationIndexRoute: AppCreationIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppCreationContentsContentIdRoute: AppCreationContentsContentIdRoute,
  AppCreationPersonasPersonaIdRoute: AppCreationPersonasPersonaIdRoute,
  AppCreationPersonasNewRoute: AppCreationPersonasNewRoute,
  AppCreationContentsIndexRoute: AppCreationContentsIndexRoute,
  AppCreationPersonasIndexRoute: AppCreationPersonasIndexRoute,
  AppCreationProfilesIndexRoute: AppCreationProfilesIndexRoute,
  AppCreationProfilesPsyProfileIdRoute: AppCreationProfilesPsyProfileIdRoute,
  AppCreationProfilesWritingProfileIdRoute:
    AppCreationProfilesWritingProfileIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
